// Mocks generated by Mockito 5.4.6 from annotations
// in faltei/test/views/disciplina_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:faltei/models/disciplina.dart' as _i3;
import 'package:faltei/viewmodels/disciplina_viewmodel.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DisciplinaViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockDisciplinaViewModel extends _i1.Mock
    implements _i2.DisciplinaViewModel {
  MockDisciplinaViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Disciplina> get disciplinas =>
      (super.noSuchMethod(
            Invocation.getter(#disciplinas),
            returnValue: <_i3.Disciplina>[],
          )
          as List<_i3.Disciplina>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadDisciplinas() =>
      (super.noSuchMethod(
            Invocation.method(#loadDisciplinas, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addDisciplina(_i3.Disciplina? disciplina) =>
      (super.noSuchMethod(
            Invocation.method(#addDisciplina, [disciplina]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateDisciplina(_i3.Disciplina? disciplina) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisciplina, [disciplina]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDisciplina(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDisciplina, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),e
    returnValueForMissingStub: null,
  );
}
